### PR TITLE
Add documentation for lts/ folder support in nodenv versions

### PR DESCRIPTION
**Pull request by lumaxis**
An initial attempt to add documentation around the feature from #154 

_Note: The documented feature is currently not yet released outside of `nodenv` installations via the git `master` branch. It probably makes sense to only merge this close to the actual wider release._

### CODE REVIEW

**Comment by lumaxis** [comment]
@jasonkarns How do you feel about this and publishing the changes from #154? I've been using them for myself for a while now and everything seems great.

**Comment by jasonkarns** [comment]
released as v1.4.0!

**Comment by isnotnull** [comment]
I think the last command in the example should be:

`$ ln -s ../12 lts/erbium`

**Comment by lumaxis** [comment]
Excellent catch, I must have typo'd that 🙂 Fix in #166

**Comment by Hnaay-Thyy** [comment]
c3a43740aceb80fee7016805873bf525db2b9578

**Comment by Hnaay-Thyy** [comment]
c3a43740aceb80fee7016805873bf525db2b9578

**Pull request merged**
