### PR TITLE
Update readme with a note about Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by jchiatt**

### CODE REVIEW

**Comment by jasonkarns** [comment]
Does WSL not use bash shell by default?

**Comment by jchiatt** [comment]
@jasonkarns I believe it does, but for some reason it prioritized `.profile` over `.bash_profile`

**Comment by jasonkarns** [comment]
Did it _prioritize_ .profile or just fall back to it? Bash will fallback to `.profile` if `.bash_profile` doesn't exist, but it should prefer `.bash_profile`. Unless WSL bash is doing something nonstandard, I would prefer to not recommend using `.profile` because that file is meant to be shell agnostic. (Other shells can and may read that file.)

Can you confirm that `.profile` is read by WSL **even when** `.bash_profile` exists? 
And also confirm whether `.bash_profile` is read when they both exist? (It _may_ be the case that some other file is causing .profile to be sourced, and that it's not strictly bash doing so as part of its startup. Perhaps an /etc/profile or other file is triggering the sourcing of ~/.profile)

https://linux.die.net/Bash-Beginners-Guide/sect_03_01.html

**Comment by jasonkarns** [comment]
You can scratch the above requests. I see now that Ubuntu is recommending alternative practices and since WSL uses Ubuntu, that would follow the same there.

Which means we probably just want to add WSL to the existing Ubuntu recommendation.

**Comment by jasonkarns** [comment]
Sorry I keep piling on 😸 

See the [related change](https://github.com/rbenv/rbenv/commit/a1fb5b1153368e3cd4d47d50965b301f81ca3ff0) in rbenv for the rationale around using .bashrc instead of .profile.

Would you mind updating this PR to just include WSL (perhaps unabbreviated? 🤷‍♂️ ) along with the existing Ubuntu option? And reference the above commit in your commit message, so the rationale is documented? Thanks!

(And rbenv would probably be glad for the same change upstream)

**Pull request merged**
