### PR TITLE
Update instructions for $PATH change in README

### PR DESCRIPTION
**Pull request by AlexWayfer**
Describe for Fish shell in details, as in https://github.com/rbenv/rbenv/pull/1083.

Reference: https://fishshell.com/docs/2.7/tutorial.html#tut_path

### CODE REVIEW

**Comment by jasonkarns** [comment]
I'm going to pull the recent changes from rbenv into nodenv today, which should hopefully resolve this. I'll leave it open until after I've done the update so you can confirm.

**Comment by AlexWayfer** [comment]
OK, thanks!

**Comment by jasonkarns** [comment]
Covered by #113

**Comment by AlexWayfer** [comment]
Nice! Thanks.

**Pull request closed without merging**
